#!/bin/bash
while [ "$select" != "No" -a "$select" != "Yes" ]; do
    select=$(echo -e 'No\nYes' | dmenu -nb '#000000' -nf '#FFFFFF' -sb '#D50000' -sf '#000000' -fn '-*-*-medium-r-normal-*-*-*-*-*-*-100-*-*' -i -p "You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.")
    [ -z "$select" ] && exit 0
done
[ "$select" = "NO" ] && exit 0
i3-msg exit
